export const LOCAL_STORAGE_NAMESPACE = '/cards'

export const LOCAL_STORAGE_KEY__SERVER_URL = `${LOCAL_STORAGE_NAMESPACE}/serverIp`

export const LOCAL_STORAGE_KEY__LAST_USED_NAME = `${LOCAL_STORAGE_NAMESPACE}/lastUsedName`
export const LOCAL_STORAGE_KEY__LAST_USED_COLOR = `${LOCAL_STORAGE_NAMESPACE}/lastUsedColor`
